version: "3.8"

services:
  db: 
    image: mysql:8.0 
    environment: 
      - MYSQL_DATABASE=appdb 
      - MYSQL_PASSWORD=pass123 
      - MYSQL_ROOT_PASSWORD=pass123 
    networks:
      -  app-network
    ports:
      - 3308:3306 
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  app-backend: 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - 3000:3000 
    networks:
      - app-network 
    depends_on:
      - db 

  app-frontend: 
    restart: always
    build: 
      context: ./frontend 
    ports:
      - 3002:3000 
    networks:
      - app-network 
    depends_on:
      - app-backend

networks:
  app-network: 
    driver: bridge 
